import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import NavBar from "@/components/NavBar";
import { WalletProvider } from "@/contexts/walletprovider";
import { ThemeProvider } from "@/components/ThemeProvider";

const lufga = localFont({
  src: [
    {
      path: './fonts/LufgaRegular.woff',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/LufgaMedium.woff',
      weight: '500',
      style: 'normal',
    },
    {
      path: './fonts/LufgaBold.woff',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-lufga',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lufga.variable} font-sans antialiased`}
      >
        <ThemeProvider
          attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
        >
          <WalletProvider>
            <NavBar></NavBar>
            <div className="px-0 pb-10 space-y-6 max-w-screen-2xl min-h-screen mx-auto">
              {children}
            </div>
          </WalletProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
